class_mode: categorical
layers:
- W_constraint: null
  W_learning_rate_multiplier: 1.0
  W_regularizer: null
  activation: linear
  activity_regularizer: null
  b_constraint: null
  b_learning_rate_multiplier: 1.0
  b_regularizer: null
  cache_enabled: true
  custom_name: dense
  init: glorot_uniform
  input_dim: null
  input_shape: !!python/tuple [50]
  name: Dense
  output_dim: 20
  trainable: true
- {activation: relu, cache_enabled: true, custom_name: activation, name: Activation,
  trainable: true}
- W_constraint: null
  W_learning_rate_multiplier: 1.0
  W_regularizer: null
  activation: linear
  activity_regularizer: null
  b_constraint: null
  b_learning_rate_multiplier: 1.0
  b_regularizer: null
  cache_enabled: true
  custom_name: dense
  init: glorot_uniform
  input_dim: null
  input_shape: !!python/tuple [20]
  name: Dense
  output_dim: 45
  trainable: true
- {activation: sigmoid, cache_enabled: true, custom_name: activation, name: Activation,
  trainable: true}
loss: binary_crossentropy
name: Sequential
optimizer: {beta_1: 0.8999999761581421, beta_2: 0.9990000128746033, epsilon: 1.0e-08,
  lr: 0.0010000000474974513, name: Adam}
