class_mode: categorical
layers:
- cache_enabled: true
  custom_name: reshape
  dims: !!python/tuple [4, 150]
  input_shape: !!python/tuple [1, 4, 150]
  name: Reshape
  trainable: true
- cache_enabled: true
  custom_name: permute
  dims: !!python/tuple [2, 1]
  name: Permute
  trainable: true
- {activation: tanh, cache_enabled: true, custom_name: gru, go_backwards: false, init: glorot_uniform,
  inner_activation: hard_sigmoid, inner_init: orthogonal, input_dim: 4, input_length: null,
  name: GRU, output_dim: 100, return_sequences: false, stateful: false, trainable: true}
- {W_constraint: null, W_learning_rate_multiplier: null, W_regularizer: null, activation: linear,
  activity_regularizer: null, b_constraint: null, b_learning_rate_multiplier: null,
  b_regularizer: null, cache_enabled: true, custom_name: dense, init: glorot_uniform,
  input_dim: null, name: Dense, output_dim: 1, trainable: true}
- {activation: sigmoid, cache_enabled: true, custom_name: activation, name: Activation,
  trainable: true}
loss: binary_crossentropy
name: Sequential
optimizer: {beta_1: 0.8999999761581421, beta_2: 0.9990000128746033, epsilon: 1.0e-08,
  lr: 0.0010000000474974513, name: Adam}
